logger:
  level: info

server:
  host: calendar
  port: 8080

grpcserver:
  host: calendar
  port: 8081

db:
  type: sql
  sql:
    driver: pgx
    name: calendar
    user: postgres
    password: postgres
    host: postgres
    port: 5432
