logger:
  level: info

server:
  host: calendar-test
  port: 8090

grpcserver:
  host: calendar-test
  port: 8091

db:
  type: sql
  sql:
    driver: pgx
    name: calendar
    user: postgres
    password: postgres
    host: postgres
    port: 5432

